version: '3.9'

services:

  nodejs:
    container_name: nodejs
    build: '.'
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    networks:
      - app-connect
    ports:
      - '3333:3333'
